version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /action
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    commit-message:
      prefix: chore
    groups:
      npm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
